const menuBtn=document.getElementById('menuBtn'),nav=document.getElementById('nav');menuBtn?.addEventListener('click',()=>nav.classList.toggle('open'));nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();document.getElementById('formMsg').textContent='Gracias. Tu consulta está lista para conectarse con el canal comercial de SEATECH.';});
const AI_API=(window.SEATECH_AI_API||localStorage.getItem('seatech_ai_api')||'').replace(/\/$/,'');
const chat=document.getElementById('aiChat'),launcher=document.getElementById('aiLauncher'),closeBtn=document.getElementById('aiClose'),msgs=document.getElementById('aiMessages'),input=document.getElementById('aiInput');
launcher?.addEventListener('click',()=>{chat.classList.add('open');launcher.style.display='none';input?.focus()});closeBtn?.addEventListener('click',()=>{chat.classList.remove('open');launcher.style.display='flex'});
function addMsg(t,c){const d=document.createElement('div');d.className='ai-msg '+c;d.textContent=t;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}
const localAnswers={proyectos:'SEATECH desarrolla sistemas marinos autónomos, robótica submarina, drones, robótica avanzada, IA y gemelos digitales.',seatech:'SEATECH Innovation & Technology integra ingeniería oceánica, robótica, inteligencia artificial y sostenibilidad.',tecnologias:'Trabajamos con USV/UAV, sensores, control autónomo, robótica, visión, IA, analítica y gemelos digitales.',colaboracion:'Podemos explorar investigación aplicada, desarrollo tecnológico, pilotos, consultoría y alianzas.'};
function localReply(q){const s=q.toLowerCase();if(s.includes('proyecto'))return localAnswers.proyectos;if(s.includes('qué es')||s.includes('que es')||s.includes('seatech'))return localAnswers.seatech;if(s.includes('colabor')||s.includes('alianza'))return localAnswers.colaboracion;return localAnswers.tecnologias}
async function reply(q){if(!AI_API){addMsg(localReply(q)+' Para activar el repositorio RAG remoto, configure SEATECH_AI_API con la URL HTTPS de ngrok.','bot');return}
 addMsg('Consultando el repositorio SEATECH…','bot');const wait=msgs.lastElementChild;
 try{const r=await fetch(AI_API+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});if(!r.ok)throw new Error('API '+r.status);const d=await r.json();wait.remove();addMsg(d.answer||d.response||'No encontré una respuesta en el repositorio.','bot')}
 catch(e){wait.remove();addMsg('El servidor AI no está disponible en este momento. Respuesta local: '+localReply(q),'bot')}}
document.querySelectorAll('.ai-chips button').forEach(b=>b.addEventListener('click',()=>{const q=b.textContent;addMsg(q,'user');reply(q)}));
document.getElementById('aiForm')?.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;addMsg(q,'user');input.value='';reply(q)});