const api=(DATAAI_CONFIG.API_BASE||"https://api-data.3seatech.com").replace(/\/$/,""),$=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString("es-PE");
async function j(p,o={}){let r=await fetch(api+p,{credentials:"include",...o});if(r.status===401){location.href="/";throw 0}if(!r.ok)throw new Error((await r.json().catch(()=>({detail:"Error"}))).detail);return r.json()}
function chart(c,v){let x=c.getContext("2d"),w=c.clientWidth,h=200,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;x.scale(d,d);x.clearRect(0,0,w,h);let m=Math.max(...v,1);x.strokeStyle="#8b5cf6";x.lineWidth=3;x.beginPath();v.forEach((n,i)=>{let px=15+i*(w-30)/(v.length-1),py=180-n/m*150;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function bars(c,v){let x=c.getContext("2d"),w=c.clientWidth,h=200,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;x.scale(d,d);x.clearRect(0,0,w,h);let m=Math.max(...v,1);v.forEach((n,i)=>{let bw=55,px=25+i*(w-60)/v.length,py=175-n/m*140;x.fillStyle="#22b8df";x.fillRect(px,py,bw,175-py);x.fillStyle="white";x.fillText(fmt(n),px,py-7)})}
async function refresh(){try{let me=await j("/api/auth/me");$("#who").textContent=me.user+" · "+me.role;$("#apiBadge").textContent="● API ONLINE";let s=await j("/api/stats");$("#records").textContent=fmt(s.rows);let u=await j("/api/uploads");$("#dataset").innerHTML=u.map(x=>'<option value="'+x.id+'">'+x.filename+'</option>').join("");$("#history").innerHTML=u.slice(0,8).map(x=>'<div>'+x.filename+' · '+fmt(x.rows)+' filas</div>').join("");chart($("#trend"),u.length?u.slice(0,10).reverse().map(x=>x.rows):[8,12,10,18,16,25,22,30])}catch(e){$("#apiBadge").textContent="● API OFFLINE"}}
$("#locate").onclick=()=>{if(!navigator.geolocation){$("#geoText").textContent="Geolocalización no disponible";return}$("#geoText").textContent="Solicitando permiso…";navigator.geolocation.getCurrentPosition(p=>{let a=p.coords.latitude,b=p.coords.longitude,acc=Math.round(p.coords.accuracy);$("#coords").textContent=a.toFixed(5)+", "+b.toFixed(5)+" · ±"+acc+" m";$("#zone").textContent="Ubicación activa";$("#geoText").textContent="Ubicación autorizada · precisión ±"+acc+" m";$("#mapLabel").textContent="Centro de análisis: "+a.toFixed(5)+", "+b.toFixed(5);},e=>{$("#geoText").textContent=e.code===1?"Permiso de ubicación denegado":"No se pudo obtener ubicación";},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})};
$("#uploadBtn").onclick=async()=>{let f=$("#dataFile").files[0];if(!f)return;let d=new FormData();d.append("file",f);try{let x=await j("/api/upload",{method:"POST",body:d});$("#toast").textContent="✓ "+x.rows+" filas × "+x.columns+" columnas";refresh()}catch(e){$("#toast").textContent=e.message}};
$("#knowledgeBtn").onclick=async()=>{let f=$("#knowledgeFile").files[0];if(!f)return;let d=new FormData();d.append("file",f);try{let x=await j("/api/knowledge/upload",{method:"POST",body:d});$("#toast").textContent="✓ Knowledge: "+x.filename}catch(e){$("#toast").textContent=e.message}};
$("#forecastBtn").onclick=async()=>{if(!$("#dataset").value)return;try{let x=await j("/api/forecast/"+$("#dataset").value);bars($("#bars"),x.forecast.slice(0,3));$("#forecast").textContent=fmt(x.forecast[0]);$("#toast").textContent="Pronóstico: "+x.column}catch(e){$("#toast").textContent=e.message}};
$("#logout").onclick=async()=>{await fetch(api+"/api/auth/logout",{method:"POST",credentials:"include"});location.href="/"};refresh();bars($("#bars"),[10,13,16]);setInterval(refresh,30000);